# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 16:17
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='readable',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
