# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 15:26
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20160614_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='mturker',
            name='accepted',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
