# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 15:32
from __future__ import unicode_literals

import data.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20160615_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mturker',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
