# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 17:15
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20160615_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='mturker',
            name='batch',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='batch',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
