# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 17:42
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20160620_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='readable',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
