# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 15:10
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_auto_20160620_1249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mturker',
            name='treatment',
        ),
        migrations.AlterField(
            model_name='task',
            name='text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
