# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 20:13
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20160622_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='mturker',
            name='wagebill',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
