# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 22:12
from __future__ import unicode_literals

import data.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20160622_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mturker',
            name='accepted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mturker',
            name='start',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 22, 22, 12, 21, 616874, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
