# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 16:37
from __future__ import unicode_literals

import data.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0017_auto_20160624_1041'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blur', models.CharField(max_length=256)),
                ('treatment', models.CharField(max_length=256)),
                ('finished', models.BooleanField(default=0)),
                ('batch', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='mturker',
            name='treatment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='mturker',
            name='start',
            field=models.DateTimeField(default=data.models.get_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
        migrations.AddField(
            model_name='mturker',
            name='treatmentcell',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.TreatmentCell'),
        ),
    ]
