# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 18:52
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0018_auto_20160624_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='treatmentcell',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='mturker',
            name='instructionsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mturker',
            name='start',
            field=models.DateTimeField(default=data.models.get_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
