# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 19:17
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0019_auto_20160708_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='blur',
        ),
        migrations.RemoveField(
            model_name='mturker',
            name='blur',
        ),
        migrations.RemoveField(
            model_name='mturker',
            name='sorting',
        ),
        migrations.RemoveField(
            model_name='mturker',
            name='treatment',
        ),
        migrations.RemoveField(
            model_name='mturker',
            name='wage',
        ),
        migrations.RemoveField(
            model_name='mturker',
            name='wagebill',
        ),
        migrations.AddField(
            model_name='image',
            name='batchNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='treatment',
            field=models.CharField(max_length=128, null=True, verbose_name=b'Exog or Endog?'),
        ),
        migrations.AddField(
            model_name='mturker',
            name='assignmentId',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='mturker',
            name='end_payment',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='mturker',
            name='end_payment_bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='mturker',
            name='finished',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='mturker',
            name='imageRound',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mturker',
            name='upfront_payment',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AddField(
            model_name='mturker',
            name='upfront_payment_bool',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='treatmentcell',
            name='csr',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='treatmentcell',
            name='sorting',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='treatmentcell',
            name='upfront',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='treatmentcell',
            name='wage',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='treatmentcell',
            name='wagebill',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=512, null=True, verbose_name=b'Filename'),
        ),
        migrations.AlterField(
            model_name='mturker',
            name='start',
            field=models.DateTimeField(default=data.models.get_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
        migrations.AlterField(
            model_name='treatmentcell',
            name='batch',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='treatmentcell',
            name='treatment',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
