# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-08 19:18
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0020_auto_20160908_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentcell',
            name='blur',
        ),
        migrations.AlterField(
            model_name='mturker',
            name='start',
            field=models.DateTimeField(default=data.models.get_now),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
