# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 15:42
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0024_auto_20160921_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentcell',
            name='csrpercent',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='treatmentcell',
            name='csrvalue',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
