# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-18 16:28
from __future__ import unicode_literals

import data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0026_auto_20161018_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatmentcell',
            name='csr',
        ),
        migrations.AlterField(
            model_name='task',
            name='timestarted',
            field=models.DateTimeField(default=data.models.get_now),
        ),
    ]
